backend/web_server/src/blueprints/auth.py
"""
Module that handles register and login
"""
import secrets

from flask import Blueprint, render_template, redirect, url_for
import bcrypt
from flask_login import login_user, logout_user
from sqlalchemy import select
import uuid
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import DataRequired, EqualTo, ValidationError, Length

from backend.models import User
from services.database import db

auth = Blueprint("auth", __name__)


class RegisterForm(FlaskForm):
    username = StringField('username', validators=[DataRequired("Username should have a value."),
                                                   Length(3, 12, "Username must be between 3-12 characters.")])
    password = StringField('password', validators=[DataRequired("Password should have a value.")])
    rep_password = StringField('rep_password',
                               validators=[DataRequired("Repeated password should have a value."),
                                           EqualTo("password", "Passwords must match.")])

    def validate_username(self, field):
        user_exists = db.session.execute(select(User).where(User.username == field.data)). \
            scalar_one_or_none()
        if user_exists:
            raise ValidationError("Username or password are invalid.")


@auth.route("/register", methods=['POST', 'GET'])
def register_route():
    """Route responsible for handling user register"""

    form = RegisterForm()

    if form.validate_on_submit():
        hashed_password = bcrypt.hashpw(bytes(form.password.data, encoding="utf-8"), bcrypt.gensalt())
        new_id = str(uuid.uuid4())
        new_user = User(username=form.username.data, password=hashed_password, id=new_id)  # type: ignore[call-arg]
        db.session.add(new_user)
        db.session.commit()
        return redirect(url_for(".login_route"))

    return render_template("auth/register.html", form=form)


class LoginForm(FlaskForm):
    username = StringField("username", validators=[DataRequired("Username must have a value.")])
    password = StringField("password", validators=[DataRequired("Password must have a value.")])

    def __init__(self, *k, **kwargs):
        super(LoginForm, self).__init__(*k, **kwargs)
        self._mem_user = None

    def validate(self, extra_validators=None):
        self._mem_user = db.session.execute(select(User).where(User.username == self.username.data)).one_or_none()
        return super(LoginForm, self).validate()

    def validate_password(self, field):
        if not self._mem_user or not bcrypt.checkpw(bytes(field.data, encoding="utf-8"), self._mem_user[0].password):
            raise ValidationError("Username or password are invalid.")


@auth.route("/login", methods=['POST', 'GET'])
def login_route():
    """Route responsible for handling user login"""
    form = LoginForm()

    if form.validate_on_submit():
        user = db.session.execute(select(User).where(User.username == form.username.data)).first()[0]
        login_user(user)
        return redirect(url_for("landing_page"))

    return render_template("auth/login.html", form=form)


@auth.route("/logout")
def logout_route():
    """Logout user from the current session"""
    logout_user()
    return redirect(url_for(".login_route"))

backend/web_server/src/blueprints/repos.py
"""
Module that handles creating, viewing and editing repositories
"""
import hashlib
import uuid

from flask import Blueprint, render_template, redirect, url_for, abort, request
from flask_wtf import FlaskForm
from sqlalchemy import select
from wtforms import StringField, RadioField, ValidationError
from wtforms.validators import DataRequired, Optional
from flask_login import login_required, current_user
import re

from services.database import db
from backend.models import Repository, User, PullRequest, Fork
from services.file_system import file_system

repo = Blueprint("repo", __name__)


class CreateRepositoryForm(FlaskForm):
    repository_name = StringField('repository_name', validators=[DataRequired("Repository name should have a value.")])
    description = StringField('description', validators=[Optional(True)])

    initial_value = RadioField('initial_value',
                               choices=[("empty", "empty repo"),
                                        ("readme", "create a repo with a default readme.md")],
                               validators=[DataRequired()])

    source_id = StringField('source_id')

    def validate_repository_name(self, field):
        exist_repo = db.session.execute(select(Repository).where(Repository.name == field.data,
                                                                 Repository.user_id == current_user.id)).one_or_none()
        if exist_repo:
            raise ValidationError("Repository name is already in use. Please choose another.")
        if not re.compile(r'^[A-Za-z0-9_.-]+$').match(field.data):
            raise ValidationError("Repository name cannot contain spaces and special characters (other then a '-').")


@repo.route("/new", methods=['POST', 'GET'])
@login_required
def new():
    """Route responsible for rendering the repo creation page"""
    form = CreateRepositoryForm()
    if form.validate_on_submit():
        created_repo_id = hashlib.sha1(
            f"{form.repository_name.data[:40]}_{current_user.username[:20]}_repository".encode()).hexdigest()
        created_repo = Repository(id=created_repo_id, name=form.repository_name.data,
                                  description=form.description.data, user_id=current_user.id)

        db.session.add(created_repo)
        db.session.commit()
        file_system.allocate_repository(created_repo_id)
        return redirect(url_for(".view_repo", username=current_user.username, repo_name=form.repository_name.data))
    return render_template("repo/new.html", form=form)


@repo.route("/<username>/<repo_name>/fork", methods=['POST'])
@login_required
def fork(username: str, repo_name: str):
    """Route for forking an existing repository"""
    current_repo = Repository.query.where(Repository.name == repo_name).first_or_404()

    if username == current_user.username:
        return redirect(url_for('.view_repo', username=username, repo_name=repo_name))

    new_id = hashlib.sha1(f"{current_repo.id[:25]}_fork_{current_user.username[:10]}".encode()).hexdigest()

    created_repo = Repository(id=new_id, name=repo_name,
                              description=current_repo.description, user_id=current_user.id)
    db.session.add(created_repo)

    created_fork = Fork(id=uuid.uuid4().hex, original_repo_id=current_repo.id, forked_repo_id=new_id)
    db.session.add(created_fork)

    db.session.commit()
    file_system.allocate_repository(new_id)
    file_system.copy_latest_commit(current_repo.id, new_id)
    return redirect(url_for(".view_repo", username=current_user.username,
                            repo_name=repo_name))


@repo.route("/<username>/<repo_name>/pulls")
def pulls(username: str, repo_name: str):
    """Route for viewing the pull requests"""
    repo_owner = User.query.where(User.username == username).first_or_404()
    current_repo = Repository.query.where(Repository.name == repo_name,
                                          Repository.user_id == repo_owner.id).first_or_404()
    pull_requests = PullRequest.query.join(User).where(PullRequest.repo_id == current_repo.id).all()
    return render_template("repo/pulls.html", repo=current_repo, prs=pull_requests)


@repo.route("/<username>/<repo_name>/")
def view_repo(username: str, repo_name: str):
    """Route responsible for viewing a user's repo"""
    branch = request.args.get("b", default="main")

    repo_owner = User.query.where(User.username == username).first_or_404()
    current_repo = Repository.query.join(User).where(Repository.name == repo_name,
                                                     Repository.user_id == repo_owner.id).first_or_404()

    repo_branches = file_system.get_repo_branches(current_repo.id)
    if branch not in repo_branches:
        abort(404)

    original_repo = Fork.query.join(Repository.original_repo_id).where(Fork.forked_repo_id == current_repo.id).first()
    if original_repo is not None:
        original_repo.user = User.query.where(User.id == original_repo.original_repo.user_id).first()

    data = file_system.get_current_commit_files(current_repo.id, branch)

    message, files = "", []
    if len(data) > 0:
        message, files = data
    head_commit = file_system.get_head_commit(current_repo.id, branch)
    return render_template("repo/view.html", repo=current_repo, files=files, original_repo=original_repo,
                           current_branch=branch,
                           repo_branches=repo_branches,

                           last_commit=head_commit, commit_message=message)


@repo.route("/<username>/<repo_name>/<branch>/<path:path>")
def view_repo_contents(username: str, repo_name: str, branch: str, path: str):
    """Route responsible for viewing a user's repo contents"""
    repo_owner = User.query.where(User.username == username).first_or_404()
    current_repo = Repository.query.join(User).where(Repository.name == repo_name,
                                                     Repository.user_id == repo_owner.id).first_or_404()
    d = file_system.get_nested_tree_contents(current_repo.id, path, branch_name=branch)
    if d is None:
        abort(404)
    tp, data = d

    if tp == "tree":
        return render_template("repo/view.html", repo=current_repo, files=data, commit_message="", last_commit="")
    else:
        file_content = file_system.get_server_object(current_repo.id, data[:2], data[2:])
        if file_content is None:
            abort(404)
        try:
            content = file_content.decode().split("\n")
            valid_encoding = True
        except UnicodeDecodeError:
            content = []
            valid_encoding = False
        return render_template("repo/view_file.html", repo=current_repo, path=path, current_branch=branch,
                               file_content=enumerate(content), commit_message="", last_commit="",
                               valid_encoding=valid_encoding)

backend/web_server/src/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>Stash</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+3:ital,wght@0,200..900;1,200..900&display=swap" rel="stylesheet">
      {% block head -%}
      {%- endblock %}
      <style>
        body  {
            font-family: "Source Sans 3", sans-serif;
            }

        @font-face {
            font-family: consolas;
            src: url(/static/fonts/CONSOLA.TTF);
        }

          .code {
            font-family: consolas;
          }
      </style>
      <script defer>
          var active = false;

          var user_menu_active = false;
          var plus_sign_menu_active = false;
          function toggle_drawer(state) {
              if (state === false) {
                  active = true;
              }

              if (!active) {
                  document.getElementById("mobile-main-sidebar").style.transform = "translate(0px, 0px)";
                  document.getElementById("main-content").style.marginLeft = "230px"
                  active = true;

                  toggle_user_menu(false)
                  toggle_plus_sign_menu(false)
              } else {
                  document.getElementById("mobile-main-sidebar").style.transform = "translate(-230px, 0px)";
                  document.getElementById("main-content").style.marginLeft = "0px"
                  active = false;
              }
          }

          function toggle_user_menu(state) {
              if (state === false) {
                  user_menu_active = true;
              }
                if (user_menu_active) {
                    document.getElementById("user_menu").style.display = "none";
                    user_menu_active = false;
                }
                  else {
                    document.getElementById("user_menu").style.display = "flex";
                    user_menu_active = true;
                    toggle_plus_sign_menu(false)
                    toggle_drawer(false)
                }
          }

            function toggle_plus_sign_menu(state) {
              if (state === false) {
                  plus_sign_menu_active = true;
              }
                if (plus_sign_menu_active) {
                    document.getElementById("plus_sign_menu").style.display = "none";
                    plus_sign_menu_active = false;
                }
                  else {
                    document.getElementById("plus_sign_menu").style.display = "flex";
                    plus_sign_menu_active = true;
                    toggle_user_menu(false)
                    toggle_drawer(false)
                }
          }



          window.onresize = function() {
            if (window.innerWidth > 768) {
                active = false
                document.getElementById("mobile-main-sidebar").style.transform = "translate(-230px, 0px)";
                document.getElementById("main-content").style.marginLeft = "0px"
            }
          }

      </script>
  </head>
  <body>
    <nav class="md:bg-[#3C8DBC] flex flex-col md:flex-row items-center justify-start fixed w-full z-50">
        <a href="{{ url_for('landing_page') }}" class="bg-[#367FA9] md:bg-[#3C8DBC] w-full text-white text-xl font-bold p-3 text-center md:text-left">StashHub</a>
        <div class="bg-[#3C8DBC] md:bg-transparent w-full flex flex-row-reverse justify-between items-center min-h-[50px]">

            {% if current_user.is_authenticated %}
                <div class="flex flex-row-reverse items-center justify-center text-black relative">
                    <div>
                        <a href="#" class="hover:bg-[#367FA9] px-4 pt-5 pb-4 text-sm" onclick="toggle_user_menu(null)">{{ current_user.username | e }}</a>
                        <div id="user_menu" class="z-10 hidden bg-white absolute w-[160px] text-sm left-[-80px] top-[42px] flex-col items-start justify-center">
                            <a href="{{ url_for('auth.logout_route') }}" class="text-gray-600 px-3 py-2 border border-t-none border-gray-200 w-full hover:bg-gray-100">Sign out</a>
                        </div>
                    </div>
                    <div>
                    <a href="#" class="text-2xl hover:bg-[#367FA9] px-4 pt-3 pb-2" onclick="toggle_plus_sign_menu(null)">+</a>
                        <div id="plus_sign_menu" class="z-10 hidden bg-white absolute w-[160px] text-sm left-[-80px] top-[42px] flex-col items-start justify-center">
                            <a href="{{ url_for('repo.new') }}" class="text-gray-600 px-3 py-2 border border-gray-200 w-full hover:bg-gray-100">New repository</a>
                        </div>
                    </div>
                </div>

            {% else %}
                <a href="{{ url_for('auth.login_route') }}" class="text-white text-sm p-4 hover:bg-[#367FA9]">Sign in</a>
            {% endif %}

            {% if self.sidebar() | trim %}
            <a href="#" class="md:hidden hover:bg-[#367FA9] h-full px-4 pb-5 pt-5" onclick="toggle_drawer()">
                <svg viewBox="0 0 100 80" width="13" height="13" fill="white">
                  <rect width="100" height="20" rx="10"></rect>
                  <rect y="35" width="100" height="20" rx="10"></rect>
                  <rect y="70" width="100" height="20" rx="10"></rect>
                </svg>
            </a>
            {% endif %}


        </div>
    </nav>



    <main class="flex flex-col md:flex-row items-start justify-start w-full h-screen pt-[90px] md:pt-[50px]">
        <div class="w-full h-full relative">
                <div id="main-content" class="w-full h-full flex flex-row justify-start items-start" style="transition: ease-in-out 0.4s">
                    {% if self.sidebar() | trim -%}
                    <div class="min-w-[230px] max-w-[230px] bg-[#222D32] text-white hidden md:block h-full">
                        {{ self.sidebar() }}
                    </div>
                    {%- endif %}

                    {% block content required -%}
                    {%- endblock %}

                </div>

                <div id="mobile-main-sidebar" class="z-10 absolute top-0 pt-4 left-0 bg-[#222D32] h-full w-[230px] text-white md:hidden" style="transition: ease-in-out 0.4s; transform: translateX(-230px)">
                    {% block sidebar -%}
                    {%- endblock %}
                </div>
        </div>
    </main>
  </body>
</html>

backend/web_server/src/templates/main_page.html
{% extends 'base.html' %}

{% macro tab_link(endpoint, name) %}
    {% if request.endpoint.endswith(endpoint) %}
        <li class="active"><a href="{{ url_for(endpoint) }}">{{name | e}}</a></li>
    {% else %}
        <li><a href="{{ url_for(endpoint) }}">{{name | e}}</a></li>
    {% endif %}
{% endmacro %}

{% block content %}
<div class="p-3 mt-10">
    <h1 class="text-[#6B9DCA] text-xl font-bold">News</h1>
    <ul class="flex-col flex gap-3 mt-2 p-3">
        {% for new_repo in new_repos %}
            <li>
                <div>
                    <h3 class="text-lg font-semibold">
                        {{ new_repo.user.username | e }} created
                        <a class="text-[#6B9DCA] underline"
                           href="{{ url_for('repo.view_repo', username=new_repo.user.username, repo_name=new_repo.name) }}">
                                {{ new_repo.name | e }}
                        </a>
                    </h3>
                    <p class="w-1/2 text-sm">
                        {% if new_repo.description %}
                            {{ new_repo.description | e }}
                        {% else %}
                            No description.
                        {% endif %}
                    </p>
                    <p>{{ new_repo.created_at.strftime("%X %x") }}</p>
                </div>
            </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}


{% block sidebar %}
<ol class="flex flex-col items-start justify-center">
    {% for repo in repos -%}
        <li class="text-gray-400 w-full text-sm">
            <a class="block px-3 py-3 hover:bg-[#1E282C] w-full" href="{{ url_for('repo.view_repo', username=current_user.username, repo_name=repo.name) }}">
            {{ current_user.username | e }}/<span class="font-semibold text-gray-300 w-full">{{ repo.name | e }}</span>
            </a>
        </li>
    {%- endfor %}
</ol>
{% endblock %}