backend/web_server/src/blueprints/repos.py
"""
Module that handles creating, viewing and editing repositories
"""
import hashlib
import uuid

from flask import Blueprint, render_template, redirect, url_for, abort, request
from flask_wtf import FlaskForm
from sqlalchemy import select
from wtforms import StringField, RadioField, ValidationError
from wtforms.validators import DataRequired, Optional
from flask_login import login_required, current_user
import re

from services.database import db
from backend.models import Repository, User, PullRequest, Fork
from services.file_system import file_system

repo = Blueprint("repo", __name__)


class CreateRepositoryForm(FlaskForm):
    repository_name = StringField('repository_name', validators=[DataRequired("Repository name should have a value.")])
    description = StringField('description', validators=[Optional(True)])

    initial_value = RadioField('initial_value',
                               choices=[("empty", "empty repo"),
                                        ("readme", "create a repo with a default readme.md")],
                               validators=[DataRequired()])

    source_id = StringField('source_id')

    def validate_repository_name(self, field):
        exist_repo = db.session.execute(select(Repository).where(Repository.name == field.data,
                                                                 Repository.user_id == current_user.id)).one_or_none()
        if exist_repo:
            raise ValidationError("Repository name is already in use. Please choose another.")
        if not re.compile(r'^[A-Za-z0-9_.-]+$').match(field.data):
            raise ValidationError("Repository name cannot contain spaces and special characters (other then a '-').")


@repo.route("/new", methods=['POST', 'GET'])
@login_required
def new():
    """Route responsible for rendering the repo creation page"""
    form = CreateRepositoryForm()
    if form.validate_on_submit():
        created_repo_id = hashlib.sha1(
            f"{form.repository_name.data[:40]}_{current_user.username[:20]}_repository".encode()).hexdigest()
        created_repo = Repository(id=created_repo_id, name=form.repository_name.data,
                                  description=form.description.data, user_id=current_user.id)

        db.session.add(created_repo)
        db.session.commit()
        file_system.allocate_repository(created_repo_id)
        return redirect(url_for(".view_repo", username=current_user.username, repo_name=form.repository_name.data))
    return render_template("repo/new.html", form=form)


@repo.route("/<username>/<repo_name>/fork", methods=['POST'])
@login_required
def fork(username: str, repo_name: str):
    """Route for forking an existing repository"""
    current_repo = Repository.query.where(Repository.name == repo_name).first_or_404()

    if username == current_user.username:
        return redirect(url_for('.view_repo', username=username, repo_name=repo_name))

    new_id = hashlib.sha1(f"{current_repo.id[:25]}_fork_{current_user.username[:10]}".encode()).hexdigest()

    created_repo = Repository(id=new_id, name=repo_name,
                              description=current_repo.description, user_id=current_user.id)
    db.session.add(created_repo)

    created_fork = Fork(id=uuid.uuid4().hex, original_repo_id=current_repo.id, forked_repo_id=new_id)
    db.session.add(created_fork)

    db.session.commit()
    file_system.allocate_repository(new_id)
    file_system.copy_latest_commit(current_repo.id, new_id)
    return redirect(url_for(".view_repo", username=current_user.username,
                            repo_name=repo_name))


@repo.route("/<username>/<repo_name>/pulls")
def pulls(username: str, repo_name: str):
    """Route for viewing the pull requests"""
    repo_owner = User.query.where(User.username == username).first_or_404()
    current_repo = Repository.query.where(Repository.name == repo_name,
                                          Repository.user_id == repo_owner.id).first_or_404()
    pull_requests = PullRequest.query.join(User).where(PullRequest.repo_id == current_repo.id).all()
    return render_template("repo/pulls.html", repo=current_repo, prs=pull_requests)


@repo.route("/<username>/<repo_name>/")
def view_repo(username: str, repo_name: str):
    """Route responsible for viewing a user's repo"""
    branch = request.args.get("b", default="main")

    repo_owner = User.query.where(User.username == username).first_or_404()
    current_repo = Repository.query.join(User).where(Repository.name == repo_name,
                                                     Repository.user_id == repo_owner.id).first_or_404()

    repo_branches = file_system.get_repo_branches(current_repo.id)
    if branch not in repo_branches:
        abort(404)

    original_repo = Fork.query.join(Repository.original_repo_id).where(Fork.forked_repo_id == current_repo.id).first()
    if original_repo is not None:
        original_repo.user = User.query.where(User.id == original_repo.original_repo.user_id).first()

    data = file_system.get_current_commit_files(current_repo.id, branch)

    message, files = "", []
    if len(data) > 0:
        message, files = data
    head_commit = file_system.get_head_commit(current_repo.id, branch)
    return render_template("repo/view.html", repo=current_repo, files=files, original_repo=original_repo,
                           current_branch=branch,
                           repo_branches=repo_branches,

                           last_commit=head_commit, commit_message=message)


@repo.route("/<username>/<repo_name>/<branch>/<path:path>")
def view_repo_contents(username: str, repo_name: str, branch: str, path: str):
    """Route responsible for viewing a user's repo contents"""
    repo_owner = User.query.where(User.username == username).first_or_404()
    current_repo = Repository.query.join(User).where(Repository.name == repo_name,
                                                     Repository.user_id == repo_owner.id).first_or_404()
    d = file_system.get_nested_tree_contents(current_repo.id, path, branch_name=branch)
    if d is None:
        abort(404)
    tp, data = d

    if tp == "tree":
        return render_template("repo/view.html", repo=current_repo, files=data, commit_message="", last_commit="")
    else:
        file_content = file_system.get_server_object(current_repo.id, data[:2], data[2:])
        if file_content is None:
            abort(404)
        try:
            content = file_content.decode().split("\n")
            valid_encoding = True
        except UnicodeDecodeError:
            content = []
            valid_encoding = False
        return render_template("repo/view_file.html", repo=current_repo, path=path, current_branch=branch,
                               file_content=enumerate(content), commit_message="", last_commit="",
                               valid_encoding=valid_encoding)

backend/web_server/src/templates/repo/new.html
{% extends 'base.html' %}

{% block head %}

<script>
    function remove_disable() {
        document.getElementById("source_id").disabled = false;
    }
    function add_disable() {
        document.getElementById("source_id").disabled = true;
    }
</script>

{% endblock %}

{% block content %}
<section class="w-full flex flex-row items-center justify-center">
    <div class="px-3 pt-6">
        <h1 class="text-2xl md:text-3xl font-bold">Create a new repository</h1>
        <p class="text-gray-600 text-sm mt-1 md:text-lg">A repository contains all your project's files, including revision history.</p>
        <div class="h-[1px] w-full bg-gray-400 mt-3"></div>
        <form class="flex flex-col items-start justify-center" action="{{ url_for('repo.new') }}" method="post">
            {{ form.csrf_token }}
            <div class="mb-1 mt-3 text-red-600">
                {% for message in form.initial_value.errors + form.repository_name.errors + form.source_id.errors%}
                    <p class="my-1">{{ message }}</p>
                {% endfor %}
            </div>
            <label for="repository_name" class="mt-4 font-semibold">Repository name</label>
            <input id="repository_name" name="repository_name" type="text" class="py-1 px-2 w-full border border-gray-300 my-1 outline-none focus:border-blue-500">
            <label for="description" class="mt-4 font-semibold">Description (optional):</label>
            <input id="description" name="description" type="text" class="py-1 px-2 w-full border border-gray-300 my-1 outline-none focus:border-blue-500">
            <div class="h-[1px] w-full bg-gray-400 mt-3"></div>
            <div class="flex flex-row items-start justify-center gap-1 mt-3">
                <input id="empty" name="initial_value" type="radio" value="empty" class="mt-1" onclick="add_disable()" checked>
                <div class="flex flex-col items-start justify-center">
                    <label for="empty" class="font-bold">Create an empty repository</label>
                    <p class="text-sm text-gray-600">Create an empty repository. You must initialize it yourself.</p>
                </div>
            </div>
            <div class="flex flex-row items-start justify-center gap-1 mt-3">
                <input id="readme" name="initial_value" type="radio" value="readme" class="mt-1" onclick="add_disable()">
                <div class="flex flex-col items-start justify-center">
                    <label for="readme" class="font-bold">Initialize this repository with a README</label>
                    <p class="text-sm text-gray-600">Create a repository and commit README.md. This is where you can write a long description for your project.</p>
                </div>
            </div>
            <div class="h-[1px] w-full bg-gray-400 mt-4"></div>
            <input type="submit" value="Create repository" class="ml-auto md:w-auto px-4 w-full text-center bg-[#00A65A] text-sm py-2 mt-3 text-white rounded hover:cursor-pointer hover:bg-green-700">
        </form>
    </div>
</section>
{% endblock %}

backend/web_server/src/templates/repo/pulls.html
{% extends 'base.html' %}

{% block content %}



<div class="w-full flex flex-col items-start justify-center p-7 mt-5 md:mt-0">
    <p class="text-[#3E6FB1] text-xl">{{ repo.user.username | e }} /
        <span class="font-semibold">{{ repo.name | e }}/</span>
    </p>
    <div class="w-full mt-5">
        <ol>
            {% for pr in prs %}
            <li>
                {{pr.user.username}} wants to merge
            </li>
            {% endfor %}
        </ol>
    </div>


</div>




{% endblock %}


{% block sidebar %}
<ol class="flex flex-col items-start justify-center text-sm">
    <li class="text-gray-400 w-full">
            <a href="{{ url_for('repo.view_repo', username=repo.user.username, repo_name=repo.name) }}" class="block px-3 py-4 hover:bg-[#1E282C] w-full hover:text-white">
                Files
            </a>
            <a href="{{ url_for('repo.pulls', username=repo.user.username, repo_name=repo.name) }}" class="block px-3 py-4 hover:bg-[#1E282C] w-full hover:text-white">
                    Pull Requests
            </a>
    </li>
</ol>
{% endblock %}

backend/web_server/src/templates/repo/view.html
{% extends 'base.html' %}

{% set repo_fingerprint = repo.user.username + "@" + repo.name + ".stash" %}



{% macro tab_link(endpoint, name) %}
    {% if request.endpoint.endswith(endpoint) %}
        <li class="active"><a href="{{ url_for(endpoint) }}">{{name}}</a></li>
    {% else %}
        <li><a href="{{ url_for(endpoint) }}">{{name}}</a></li>
    {% endif %}
{% endmacro %}


{% macro file_view(type, file_name) %}
      <tr class="border-b border-gray-100 hover:bg-[#F5F5F5]">
        <td class="px-4 py-2 text-[#3C8DBC]">
            <a href="{{ url_for('repo.view_repo_contents',username=repo.user.username,branch=current_branch, repo_name=repo.name, path=file_name ) }}" class="flex flex-row items-center justify-start gap-2">
                {% if type == "blob" %}
            <svg xmlns="http://www.w3.org/2000/svg" fill="#ACACAC" viewBox="0 0 16 16" width="16" height="16">
                <path d="M2 1.75C2 .784 2.784 0 3.75 0h6.586c.464 0 .909.184 1.237.513l2.914 2.914c.329.328.513.773.513 1.237v9.586A1.75 1.75 0 0 1 13.25 16h-9.5A1.75 1.75 0 0 1 2 14.25Zm1.75-.25a.25.25 0 0 0-.25.25v12.5c0 .138.112.25.25.25h9.5a.25.25 0 0 0 .25-.25V6h-2.75A1.75 1.75 0 0 1 9 4.25V1.5Zm6.75.062V4.25c0 .138.112.25.25.25h2.688l-.011-.013-2.914-2.914-.013-.011Z">
                </path>
            </svg>
            {% else %}
            <svg xmlns="http://www.w3.org/2000/svg" fill="#ACACAC" viewBox="0 0 16 16" width="16" height="16"><path d="M1.75 1A1.75 1.75 0 0 0 0 2.75v10.5C0 14.216.784 15 1.75 15h12.5A1.75 1.75 0 0 0 16 13.25v-8.5A1.75 1.75 0 0 0 14.25 3H7.5a.25.25 0 0 1-.2-.1l-.9-1.2C6.07 1.26 5.55 1 5 1H1.75Z"></path></svg>
            {% endif %}
            {{ file_name.split("/") | last | e }}
            </a></td>
        <td class="px-4 py-2 text-black"></td>
        <td class="px-4 py-2 text-black"></td>
      </tr>
{% endmacro %}

{% block content %}


<script>
    function copy_stash_url() {
      var copyText = "{{ repo_fingerprint | e }}"
      navigator.clipboard.writeText(copyText);
    }

    function handleSelect(elm)
      {
         window.location = "?b=" + elm.value;
      }
</script>



<div class="w-full flex flex-col items-start justify-center p-7 mt-5 md:mt-0">
    <p class="text-[#3E6FB1] text-xl">{{ repo.user.username | e }} /
        <span class="font-semibold">{{ repo.name | e }}/{{ "/".join(request.path.split("/")[3:]) | e }}</span>
    </p>
    {% if original_repo %}
        <a href="{{ url_for('repo.view_repo', username=original_repo.user.username, repo_name=original_repo.original_repo.name) }}" class="text-sm mt-2 text-blue-600">
            Fork of {{ original_repo.user.username }}/{{ original_repo.original_repo.name }}
        </a>
    {% endif %}

    {% if files | length == 0 %}
    <h2 class="text-3xl mt-5"><span class="font-semibold">Quick setup</span> - if you've done this kind of thing before</h2>
    <p class="mt-2">via TCP</p>
    <div class="mt-7 w-full">
        <h4 class="text-2xl mb-2">Create a new repository from the command line</h4>
        <div class="bg-[#F5F5F5] py-3 px-2 rounded border-2 border-[#E0E0E0] w-full">
            <code>echo "# Hello World" >> touch README.md <br/></code>
            <code>stash init <br/></code>
            <code>stash add README.md <br/></code>
            <code>stash commit "first commit" <br/></code>
            <code>stash remote add origin {{ repo_fingerprint | e }}<br /></code>
            <code>stash push origin</code>
        </div>
    </div>
    <div class="mt-7 w-full">
        <h4 class="text-2xl mb-2">Push an existing repository from the command line</h4>
        <div class="bg-[#F5F5F5] py-3 px-2 rounded border-2 border-[#E0E0E0] w-full">
            <code>stash remote add origin {{ repo_fingerprint | e }}<br /></code>
            <code>stash push origin</code>
        </div>
    </div>
    {% else %}
    <p class="mt-2 w-2/4">{{ repo.description | e }}</p>
    <div class="w-full mt-5">
        <div class="flex flex-row items-center justify-between w-full text-sm h-[40px]">
            <div class="flex flex-row items-center justify-start gap-3 h-[40px] text-sm">
            <span class="bg-[#F4F4F4] px-2 py-1 rounded border text-[#ACACAC]">
                branch:
                <select onchange="javascript:handleSelect(this)" name="branches" class="pl-1 py-1 bg-transparent font-bold text-gray-600">
                    <option value="">{{ current_branch }}</option>
                    {% for branch in repo_branches %}
                        {% if branch !=  current_branch %}
                            <option value="{{branch}}">{{ branch }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </span>
            <span class="pl-2 border border-gray-300 rounded my-1 text-gray-300 cursor-pointer text-sm" onclick="copy_stash_url()">
                {{ repo_fingerprint | e }}
                <button class="ml-2 p-2 bg-[#F5F5F5] text-gray-600 font-semibold">copy</button>
            </span>


            </div>
            {% if current_user.is_authenticated and current_user.id != repo.user.id %}
                <form action="{{ url_for('repo.fork', username=repo.user.username, repo_name=repo.name) }}" method="post">
                        <input type="submit" value="Fork" class="cursor-pointer bg-green-500 py-2 px-5 rounded text-white border border-gray-300">
                </form>
            {% endif %}
        </div>
         <table class="w-full text-sm text-gray-700 dark:text-gray-400 mt-2">
              <tr class="bg-[#F4F4F4] text-gray-600">
                <th class="px-4 py-2 text-left text-[#7F7F7F] font-normal">{{ commit_message[:20] | e }}</th>
                <th class="px-4 py-2"></th>
                <th class="px-4 py-2 text-right"><span class="font-normal text-[#ACACAC] mr-2">latest commit</span>{{ last_commit[:10] | e }}</th>
              </tr>
                 {% for file in files %}
                 {{ file_view(file[0], file[2]) }}
                 {% endfor %}
        </table>
    </div>

    {% endif %}


</div>




{% endblock %}


{% block sidebar %}
<ol class="flex flex-col items-start justify-center text-sm">
    <li class="text-gray-400 w-full">
            <a href="{{ url_for('repo.view_repo', username=repo.user.username, repo_name=repo.name) }}" class="block px-3 py-4 hover:bg-[#1E282C] w-full hover:text-white">
                Files
            </a>
            <a href="{{ url_for('repo.pulls', username=repo.user.username, repo_name=repo.name) }}" class="block px-3 py-4 hover:bg-[#1E282C] w-full hover:text-white">
                    Pull Requests
            </a>
    </li>
</ol>
{% endblock %}

backend/web_server/src/templates/repo/view_file.html
{% extends 'base.html' %}

{% macro tab_link(endpoint, name) %}
    {% if request.endpoint.endswith(endpoint) %}
        <li class="active"><a href="{{ url_for(endpoint) }}">{{name}}</a></li>
    {% else %}
        <li><a href="{{ url_for(endpoint) }}">{{name}}</a></li>
    {% endif %}
{% endmacro %}

{% block content %}


<script>
    function copy_stash_url() {
      var copyText = "{{ repo.user.username | e }}@{{ repo.name | e }}.stash"
      navigator.clipboard.writeText(copyText);
    }
</script>



<div class="w-full flex flex-col items-start justify-center p-7 mt-5 md:mt-0">
    <p class="text-[#3E6FB1] text-xl">{{ repo.user.username | e }} / <span class="font-semibold">{{ repo.name | e }}/{{ path | e }}</span></p>

    <div class="w-full mt-5">
        <div class="flex flex-row items-center justify-start gap-3 h-[40px] text-sm">
            <span class="bg-[#F4F4F4] px-2 py-1 rounded border text-[#ACACAC]">
                branch:
                <select name="branches" class="pl-1 py-1 bg-transparent font-bold text-gray-600">
                  <option value="main">main</option>
                    <option value="dev">dev</option>
                </select>
            </span>
            <span class="pl-2 border border-gray-300 rounded my-1 text-gray-300 cursor-pointer text-sm" onclick="copy_stash_url()">
                {{ repo.user.username | e }}@{{ repo.name | e }}.stash
                <button class="ml-2 p-2 bg-[#F5F5F5] text-gray-600 font-semibold">copy</button>
            </span>

        </div>
         <table class="w-full text-sm text-gray-700 dark:text-gray-400 mt-2">
              <tr class="bg-[#F4F4F4] text-gray-600">
                <th class="px-4 py-2 text-left text-gray-700 text-lg font-semibold code">{{ path.split("/") | last | e }}</th>
                <th class="px-4 py-2"></th>
                <th class="px-4 py-2"></th>
              </tr>
        </table>
        <div class="border border-[#C0C0C0] mt-1 h-[600px] overflow-scroll">
        {% for index, val in file_content %}
                <div class="flex flex-row items-center justify-start gap-3">
                    <span class="code w-[50px] text-center bg-[#F5F5F5] block py-1 px-2 text-[#6C6C6C] border-r border-r-[#C0C0C0] text-sm">
                        {{ index }}
                    </span>
                    <pre class="code">{{ val }}</pre>
                </div>
        {% endfor %}

            {% if not valid_encoding %}
            <div class="p-3">
                <p>Sorry, but we can't show you a preview of this file.</p>
                <p>The file seems to be in a non-readable format.</p>
            </div>
            {% endif %}

        </div>
    </div>




</div>




{% endblock %}


{% block sidebar %}
<ol class="flex flex-col items-start justify-center text-sm">
    <li class="text-gray-400 w-full">
            <a href="{{ url_for('repo.view_repo', username=repo.user.username, repo_name=repo.name) }}" class="block px-3 py-4 hover:bg-[#1E282C] w-full hover:text-white">
                Files
            </a>
            <a href="{{ url_for('repo.pulls', username=repo.user.username, repo_name=repo.name) }}" class="block px-3 py-4 hover:bg-[#1E282C] w-full hover:text-white">
                    Pull Requests
            </a>
    </li>
</ol>
{% endblock %}